WeatherApp/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "forecasts#index"
  
 
    resources :forecasts

end

WeatherApp/app/models/forecast.rb
class Forecast < ActiveRecord::Base
    
  
end

WeatherApp/app/models/location.rb
class Location < ActiveRecord::Base
end

WeatherApp/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
   
end

WeatherApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

WeatherApp/app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  
  before_action :authenticate_user!, :except => [:index]

    
    def index
        @forecast = Forecast.new
        
        if user_signed_in?
            @forecasts = Forecast.where(user_id: current_user.id)
        end    
        
        # Define city and state
        
        if params[:city]
            @city = params[:city]
            @state = params[:state]
        elsif user_signed_in? && Forecast.where(user_id: current_user.id).exists?
            @city = Forecast.where(user_id: current_user.id).first["city_name"]
            @state = Forecast.where(user_id: current_user.id).first["state_code"]
        
        else
            @city = "San Francisco"
            @state = "CA"
        end
        
        # Get weather from API
        
        request = Typhoeus::Request.new(
			    URI.encode("http://api.wunderground.com/api/#{ENV["wunderground_api_key"]}/forecast/q/#{@state}/#{@city.gsub(" ", "_")}.json"), method: :get)
	    request.run
	    weather_json = JSON.parse(request.response.body)
		@weather = weather_json["forecast"]["simpleforecast"]["forecastday"]
		
	    # Get internal logic file
	    
	    require 'json'
        file = File.read("#{Rails.root}/public/data.json")
        logic = JSON.parse(file)
        
        # Create array of days with hash of weather and clothing values
        
        @forecast_hash = []
        
        @weather.each do |day|
           
           forecast = {
                "weekday" => day["date"]["weekday"],
                "high_temp"=> day["high"]["fahrenheit"],
                "low_temp"=> day["low"]["fahrenheit"],
                "conditions"=> day["conditions"],
                "rain" => day["pop"]
                }
           
           @high_temp = day["high"]["fahrenheit"].to_i
           
           logic["ranges"].each do |h| 
                if h["max_temp"] >= @high_temp && h["min_temp"] <= @high_temp
                    @outfit = h["outfits"].sample
                end    
            end
            
            clothing = []
            image_urls = []
            
            @outfit.each do |item|
                @item = item
                
                request = Typhoeus::Request.new(
		            URI.encode("http://api.shopstyle.com/api/v2/products?pid=#{ENV["shopstyle_api_key"]}&fts=womens+#{@item.gsub(" ", "+")}&offset=#{rand(14)}&limit=15"), method: :get)
		        request.run
	            fashion_json = JSON.parse(request.response.body)
	            
	            clothing << item
	        	image_urls << fashion_json["products"][0]["image"]["sizes"]["IPhone"]["url"]    
            end
            
            forecast["clothes"] = clothing
            forecast["image_url"] = image_urls
            
            @forecast_hash << forecast
            
        end    
      
    end
    
    
    def create
        
        new_forecast = Forecast.create(forecast_params)
        
        redirect_to "/"
        
    end  
    
    def destroy
       Forecast.find(params[:id]).destroy
       redirect_to "/"
    end    
    
private 

    def forecast_params
        params.require(:forecast).permit(:city_name, :state_code, :user_id).merge(user_id: current_user.id)
    end    
    
end

WeatherApp/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

    def sign_up_params
        params.require(:user).permit(:email, :password, :password_confirmation, :gender)
    end

    def account_update_params
        params.require(:user).permit(:email, :password, :password_confirmation, :gender)
    end

end

WeatherApp/app/helpers/application_helper.rb
module ApplicationHelper
end

WeatherApp/app/helpers/forecasts_helper.rb
module ForecastsHelper

    
    
end

WeatherApp/app/views/forecasts/index.html.erb
<%= render "partials/header_nav" %>

  <main class="mdl-layout__content">

    
    <div class="mdl-grid">
        <div class="search mdl-cell mdl-cell--12-col mdl-cell--top">
                <h2>What to wear in...</h2>
                 <form action="/forecasts" method="get">
                    <div class="mdl-textfield mdl-js-textfield">
                        <input class="mdl-textfield__input" type="text"  name="city" pattern="[A-Z,a-z, ]*">
                        <label class="mdl-textfield__label" for="city" style="font-size: 150%"><em><%= @city %></em></label>
                        <span class="mdl-textfield__error">Enter a city name</span>
                    </div>
                    <div class="state mdl-textfield mdl-js-textfield">
                        <input class="mdl-textfield__input" type="text"  name="state" pattern="[A-Z]{2}">
                        <label class="mdl-textfield__label" for="state" style="font-size: 150%"><em><%= @state %></em></label>
                        <span class="mdl-textfield__error">Enter the 2-letter state abbreviation</span>
                    </div>
                    <button class="mdl-button mdl-js-button mdl-button--icon" type="submit">
                        <i class="material-icons">search</i>
                    </button>
                </form>
        </div
    </div>
    
    
    <div class="mdl-grid">
        <% @forecast_hash.each do |day| %>    
        <div class="weather mdl-cell mdl-cell--3-col mdl-cell--top">
        <div class="weather-card mdl-card mdl-shadow--4dp">
            <div class="weather mdl-card__supporting-text">
                <h4><%= day["weekday"].upcase %></h4>
             
                <h3><%= day["high_temp"] %>&deg;</h3>
                <h4><%= day["low_temp"] %>&deg;</h4>
                <p><%= day["conditions"] %></p>
                <p><%= day["rain"] %>% chance of rain</p>
              </div>
             <div class="mdl-card__supporting-text">
              <img src="<%= day["image_url"][0] %>" width="100%">
              <h6><%= day["clothes"][0] %></h6>
              <img src="<%= day["image_url"][1] %>" width="100%">
              <p><%= day["clothes"][1]  %></p>
              <img src="<%= day["image_url"][2] %>" width="100%">
              <p><%= day["clothes"][2]  %></p>
              </div>
            </div>
        </div>
        <% end %>
    </div>
    
 
    


  </main>
</div>

WeatherApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeatherStyle</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>

<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.indigo-green.min.css" />
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Josefin+Slab:400,300,600' rel='stylesheet' type='text/css'>



</head>
<body>


<%= yield %>

<!-- jQuery -->
<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js"></script>



<%= javascript_include_tag 'application' %>

</body>
</html>

WeatherApp/app/views/partials/_header_nav.html.erb
<!-- The drawer is always open in large screens. The header is always shown,
  even in small screens. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer
            mdl-layout--fixed-header">
  <div class="mdl-layout__drawer mdl-color--indigo-500 mdl-color-text--grey-50">
  <header class="locations-drawer-header">
    <h1>WeatherStyle</h1>
    <hr>
  </header>
  
    <nav class="location mdl-navigation">
        <h6 style="text-align: center">SAVED LOCATIONS</h6>
        <% if user_signed_in? %>
                <div class="location-links">
                <table>
                <% @forecasts.each do |location| %>
                <tr>
                    <td>
                        <a href="/forecasts?city=<%= location.city_name %>&state=<%= location.state_code %>"><%= location.city_name %></a>
                    </td>
                    <td class="delete">
                    <%= form_tag(forecast_path(location.id), method: "DELETE") do %>
                    <button type="submit" class="mdl-button mdl-js-button mdl-button--icon"><i class="material-icons">delete</i></button>
                    <% end %>
                    </td>
                </tr>
                <% end %>
                </table>
                </div>
        <% end %>
        
      <div class="add-location">
      <%= form_for @forecast do |f| %>
        <%= f.hidden_field :city_name, :value => @city %>
        <%= f.hidden_field :state_code, :value => @state %>
        <button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored mdl-color--teal-A100" type="submit">
            <i class="material-icons">add</i>
        </button>
      <% end %>
      </div>

      <div class="account-links">

            <% if user_signed_in? %>
                <%= link_to "Sign out", destroy_user_session_path, method: "DELETE" %>
            <% end %>
            <% if !user_signed_in? %>
                <%= link_to "Sign in", new_user_session_path %>
                <br/>
                <%= link_to "Sign up", new_user_registration_path %>
            <% end %>
      <div>
     
    </nav>
  </div>